### PR TITLE
BENCH-213 (removing optional from description)

### PR DESCRIPTION
**Pull request by SWhyteAnswer**

### CODE REVIEW

**Comment by JavedK15** [comment]
Do we want to make sure that the form validation also enforces this?

**Comment by SWhyteAnswer** [comment]
@JavedK15 Yeah your right. But spoke to Min and it looks like the api should actually accept nullable.So raised it on the C# chat. I'll wait to here back and then either make changes or remove PR

**Comment by SWhyteAnswer** [comment]
@JavedK15 Jake says description is required so will make changes.

**Review by mbaltrimas — CHANGES_REQUESTED** [review]
might want to also update the model to reflect this change

**Review by JavedK15 — DISMISSED** [review]

**Review by harrystead2 — DISMISSED** [review]

**Review by mbaltrimas — APPROVED** [review]

**Review by harrystead2 — APPROVED** [review]

**Review by JavedK15 — APPROVED** [review]

**Pull request merged**
