### PR TITLE
Enforce node 18 and npm 8

### PR DESCRIPTION
**Pull request by mbaltrimas**

### CODE REVIEW

**Review by milkshakeuk — DISMISSED** [review]
looks good!

**Review by bethcryer — COMMENTED** [review]
The dockerfile is using node 19, could maybe change that to node 18 too?

**Comment by mbaltrimas** [comment]
> The dockerfile is using node 19, could maybe change that to node 18 too?

updated @bethcryer

**Review by bethcryer — APPROVED** [review]

**Review by milkshakeuk — APPROVED** [review]
Looks good

**Pull request merged**
